esphome:
  name: led-light-kitchen-esp32
  friendly_name: "Led Light Kitchen"
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API (alternative to MQTT)
api:
  encryption:
    key: "key"

# Enable OTA updates
ota:
  - platform: esphome
    password: "pass"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

output:
  - platform: ledc
    pin: GPIO27
    id: led_output
    frequency: 1000 Hz
    max_power: 0.7

light:
  - platform: monochromatic
    name: "LED Kitchen"
    output: led_output
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON